title: "Yoon's Blog"
description: "Welcome to my git blog that you can see my studies"
theme: just-the-docs

url: https://Themath93.github.io

aux_links:
  Template Repository: https://github.com/Themath93/just-the-docs-template

plugins:
  - jekyll-default-layout